export enum Outcomes {
    // Runs
    SINGLE = 'SINGLE',
    DOUBLE = 'DOUBLE',
    TRIPLE = 'TRIPLE',
    FOUR_RUNS = 'FOUR_RUNS',
    FOUR_BOUNDARY = 'FOUR_BOUNDARY',
    SIX_BOUNDARY = 'SIX_BOUNDARY',

    // Extras
    WIDE = 'WIDE',
    WIDE_FOUR = 'WIDE_FOUR',
    NO_BALL = 'NO_BALL',
    NO_BALL_FOUR = 'NO_BALL_FOUR',
    NO_BALL_SIX = 'NO_BALL_SIX',
    DEAD_BALL = 'DEAD_BALL',

    // Wickets
    WICKET_BOWLED = 'WICKET_BOWLED',
    WICKET_CAUGHT = 'WICKET_CAUGHT',
    WICKET_STUMP = 'WICKET_STUMP',
    WICKET_RUN_OUT = 'WICKET_RUN_OUT',

    DOT_BALL = 'DOT_BALL',
}